<?php
/**
 * AccountipstatApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * AccountipstatApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountipstatApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation iPStatRouterGetAllAggregateIPStats
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ModelsStat
     */
    public function iPStatRouterGetAllAggregateIPStats($x_account_api_key, $ipid, $from = null, $to = null)
    {
        list($response) = $this->iPStatRouterGetAllAggregateIPStatsWithHttpInfo($x_account_api_key, $ipid, $from, $to);
        return $response;
    }

    /**
     * Operation iPStatRouterGetAllAggregateIPStatsWithHttpInfo
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ModelsStat, HTTP status code, HTTP response headers (array of strings)
     */
    public function iPStatRouterGetAllAggregateIPStatsWithHttpInfo($x_account_api_key, $ipid, $from = null, $to = null)
    {
        $returnType = '\Swagger\Client\Model\ModelsStat';
        $request = $this->iPStatRouterGetAllAggregateIPStatsRequest($x_account_api_key, $ipid, $from, $to);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ModelsStat',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation iPStatRouterGetAllAggregateIPStatsAsync
     *
     * 
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function iPStatRouterGetAllAggregateIPStatsAsync($x_account_api_key, $ipid, $from = null, $to = null)
    {
        return $this->iPStatRouterGetAllAggregateIPStatsAsyncWithHttpInfo($x_account_api_key, $ipid, $from, $to)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation iPStatRouterGetAllAggregateIPStatsAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function iPStatRouterGetAllAggregateIPStatsAsyncWithHttpInfo($x_account_api_key, $ipid, $from = null, $to = null)
    {
        $returnType = '\Swagger\Client\Model\ModelsStat';
        $request = $this->iPStatRouterGetAllAggregateIPStatsRequest($x_account_api_key, $ipid, $from, $to);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'iPStatRouterGetAllAggregateIPStats'
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function iPStatRouterGetAllAggregateIPStatsRequest($x_account_api_key, $ipid, $from = null, $to = null)
    {
        // verify the required parameter 'x_account_api_key' is set
        if ($x_account_api_key === null || (is_array($x_account_api_key) && count($x_account_api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_account_api_key when calling iPStatRouterGetAllAggregateIPStats'
            );
        }
        // verify the required parameter 'ipid' is set
        if ($ipid === null || (is_array($ipid) && count($ipid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ipid when calling iPStatRouterGetAllAggregateIPStats'
            );
        }

        $resourcePath = '/account/ip/stat/{ipid}/aggregate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // header params
        if ($x_account_api_key !== null) {
            $headerParams['X-Account-ApiKey'] = ObjectSerializer::toHeaderValue($x_account_api_key);
        }

        // path params
        if ($ipid !== null) {
            $resourcePath = str_replace(
                '{' . 'ipid' . '}',
                ObjectSerializer::toPathValue($ipid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation iPStatRouterGetAllAggregateIPStatsByGroup
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $provider the group whose stats you want (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ModelsStat
     */
    public function iPStatRouterGetAllAggregateIPStatsByGroup($x_account_api_key, $ipid, $provider, $from = null, $to = null)
    {
        list($response) = $this->iPStatRouterGetAllAggregateIPStatsByGroupWithHttpInfo($x_account_api_key, $ipid, $provider, $from, $to);
        return $response;
    }

    /**
     * Operation iPStatRouterGetAllAggregateIPStatsByGroupWithHttpInfo
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $provider the group whose stats you want (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ModelsStat, HTTP status code, HTTP response headers (array of strings)
     */
    public function iPStatRouterGetAllAggregateIPStatsByGroupWithHttpInfo($x_account_api_key, $ipid, $provider, $from = null, $to = null)
    {
        $returnType = '\Swagger\Client\Model\ModelsStat';
        $request = $this->iPStatRouterGetAllAggregateIPStatsByGroupRequest($x_account_api_key, $ipid, $provider, $from, $to);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ModelsStat',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation iPStatRouterGetAllAggregateIPStatsByGroupAsync
     *
     * 
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $provider the group whose stats you want (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function iPStatRouterGetAllAggregateIPStatsByGroupAsync($x_account_api_key, $ipid, $provider, $from = null, $to = null)
    {
        return $this->iPStatRouterGetAllAggregateIPStatsByGroupAsyncWithHttpInfo($x_account_api_key, $ipid, $provider, $from, $to)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation iPStatRouterGetAllAggregateIPStatsByGroupAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $provider the group whose stats you want (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function iPStatRouterGetAllAggregateIPStatsByGroupAsyncWithHttpInfo($x_account_api_key, $ipid, $provider, $from = null, $to = null)
    {
        $returnType = '\Swagger\Client\Model\ModelsStat';
        $request = $this->iPStatRouterGetAllAggregateIPStatsByGroupRequest($x_account_api_key, $ipid, $provider, $from, $to);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'iPStatRouterGetAllAggregateIPStatsByGroup'
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $provider the group whose stats you want (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function iPStatRouterGetAllAggregateIPStatsByGroupRequest($x_account_api_key, $ipid, $provider, $from = null, $to = null)
    {
        // verify the required parameter 'x_account_api_key' is set
        if ($x_account_api_key === null || (is_array($x_account_api_key) && count($x_account_api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_account_api_key when calling iPStatRouterGetAllAggregateIPStatsByGroup'
            );
        }
        // verify the required parameter 'ipid' is set
        if ($ipid === null || (is_array($ipid) && count($ipid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ipid when calling iPStatRouterGetAllAggregateIPStatsByGroup'
            );
        }
        // verify the required parameter 'provider' is set
        if ($provider === null || (is_array($provider) && count($provider) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $provider when calling iPStatRouterGetAllAggregateIPStatsByGroup'
            );
        }

        $resourcePath = '/account/ip/stat/{ipid}/aggregate/provider';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // query params
        if ($provider !== null) {
            $queryParams['provider'] = ObjectSerializer::toQueryValue($provider);
        }
        // header params
        if ($x_account_api_key !== null) {
            $headerParams['X-Account-ApiKey'] = ObjectSerializer::toHeaderValue($x_account_api_key);
        }

        // path params
        if ($ipid !== null) {
            $resourcePath = str_replace(
                '{' . 'ipid' . '}',
                ObjectSerializer::toPathValue($ipid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation iPStatRouterGetAllAggregatedProviderStatsForAIP
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ModelsPIPStat[]
     */
    public function iPStatRouterGetAllAggregatedProviderStatsForAIP($x_account_api_key, $ipid, $from = null, $to = null)
    {
        list($response) = $this->iPStatRouterGetAllAggregatedProviderStatsForAIPWithHttpInfo($x_account_api_key, $ipid, $from, $to);
        return $response;
    }

    /**
     * Operation iPStatRouterGetAllAggregatedProviderStatsForAIPWithHttpInfo
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ModelsPIPStat[], HTTP status code, HTTP response headers (array of strings)
     */
    public function iPStatRouterGetAllAggregatedProviderStatsForAIPWithHttpInfo($x_account_api_key, $ipid, $from = null, $to = null)
    {
        $returnType = '\Swagger\Client\Model\ModelsPIPStat[]';
        $request = $this->iPStatRouterGetAllAggregatedProviderStatsForAIPRequest($x_account_api_key, $ipid, $from, $to);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ModelsPIPStat[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation iPStatRouterGetAllAggregatedProviderStatsForAIPAsync
     *
     * 
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function iPStatRouterGetAllAggregatedProviderStatsForAIPAsync($x_account_api_key, $ipid, $from = null, $to = null)
    {
        return $this->iPStatRouterGetAllAggregatedProviderStatsForAIPAsyncWithHttpInfo($x_account_api_key, $ipid, $from, $to)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation iPStatRouterGetAllAggregatedProviderStatsForAIPAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function iPStatRouterGetAllAggregatedProviderStatsForAIPAsyncWithHttpInfo($x_account_api_key, $ipid, $from = null, $to = null)
    {
        $returnType = '\Swagger\Client\Model\ModelsPIPStat[]';
        $request = $this->iPStatRouterGetAllAggregatedProviderStatsForAIPRequest($x_account_api_key, $ipid, $from, $to);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'iPStatRouterGetAllAggregatedProviderStatsForAIP'
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function iPStatRouterGetAllAggregatedProviderStatsForAIPRequest($x_account_api_key, $ipid, $from = null, $to = null)
    {
        // verify the required parameter 'x_account_api_key' is set
        if ($x_account_api_key === null || (is_array($x_account_api_key) && count($x_account_api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_account_api_key when calling iPStatRouterGetAllAggregatedProviderStatsForAIP'
            );
        }
        // verify the required parameter 'ipid' is set
        if ($ipid === null || (is_array($ipid) && count($ipid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ipid when calling iPStatRouterGetAllAggregatedProviderStatsForAIP'
            );
        }

        $resourcePath = '/account/ip/stat/{ipid}/aggregate/providers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // header params
        if ($x_account_api_key !== null) {
            $headerParams['X-Account-ApiKey'] = ObjectSerializer::toHeaderValue($x_account_api_key);
        }

        // path params
        if ($ipid !== null) {
            $resourcePath = str_replace(
                '{' . 'ipid' . '}',
                ObjectSerializer::toPathValue($ipid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIP
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  int $sid the Sub Account Id you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ModelsPIPStat[]
     */
    public function iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIP($x_account_api_key, $ipid, $sid, $from = null, $to = null)
    {
        list($response) = $this->iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIPWithHttpInfo($x_account_api_key, $ipid, $sid, $from, $to);
        return $response;
    }

    /**
     * Operation iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIPWithHttpInfo
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  int $sid the Sub Account Id you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ModelsPIPStat[], HTTP status code, HTTP response headers (array of strings)
     */
    public function iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIPWithHttpInfo($x_account_api_key, $ipid, $sid, $from = null, $to = null)
    {
        $returnType = '\Swagger\Client\Model\ModelsPIPStat[]';
        $request = $this->iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIPRequest($x_account_api_key, $ipid, $sid, $from, $to);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ModelsPIPStat[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIPAsync
     *
     * 
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  int $sid the Sub Account Id you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIPAsync($x_account_api_key, $ipid, $sid, $from = null, $to = null)
    {
        return $this->iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIPAsyncWithHttpInfo($x_account_api_key, $ipid, $sid, $from, $to)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIPAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  int $sid the Sub Account Id you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIPAsyncWithHttpInfo($x_account_api_key, $ipid, $sid, $from = null, $to = null)
    {
        $returnType = '\Swagger\Client\Model\ModelsPIPStat[]';
        $request = $this->iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIPRequest($x_account_api_key, $ipid, $sid, $from, $to);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIP'
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  int $sid the Sub Account Id you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIPRequest($x_account_api_key, $ipid, $sid, $from = null, $to = null)
    {
        // verify the required parameter 'x_account_api_key' is set
        if ($x_account_api_key === null || (is_array($x_account_api_key) && count($x_account_api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_account_api_key when calling iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIP'
            );
        }
        // verify the required parameter 'ipid' is set
        if ($ipid === null || (is_array($ipid) && count($ipid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ipid when calling iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIP'
            );
        }
        // verify the required parameter 'sid' is set
        if ($sid === null || (is_array($sid) && count($sid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sid when calling iPStatRouterGetAllAggregatedProviderStatsForASpecificSubAccountOfAIP'
            );
        }

        $resourcePath = '/account/ip/stat/{ipid}/aggregate/sid/{sid}/providers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // header params
        if ($x_account_api_key !== null) {
            $headerParams['X-Account-ApiKey'] = ObjectSerializer::toHeaderValue($x_account_api_key);
        }

        // path params
        if ($ipid !== null) {
            $resourcePath = str_replace(
                '{' . 'ipid' . '}',
                ObjectSerializer::toPathValue($ipid),
                $resourcePath
            );
        }
        // path params
        if ($sid !== null) {
            $resourcePath = str_replace(
                '{' . 'sid' . '}',
                ObjectSerializer::toPathValue($sid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation iPStatRouterGetAllAggregatedSubAccountStatsForAnIP
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ModelsSIPStat[]
     */
    public function iPStatRouterGetAllAggregatedSubAccountStatsForAnIP($x_account_api_key, $ipid, $from = null, $to = null)
    {
        list($response) = $this->iPStatRouterGetAllAggregatedSubAccountStatsForAnIPWithHttpInfo($x_account_api_key, $ipid, $from, $to);
        return $response;
    }

    /**
     * Operation iPStatRouterGetAllAggregatedSubAccountStatsForAnIPWithHttpInfo
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ModelsSIPStat[], HTTP status code, HTTP response headers (array of strings)
     */
    public function iPStatRouterGetAllAggregatedSubAccountStatsForAnIPWithHttpInfo($x_account_api_key, $ipid, $from = null, $to = null)
    {
        $returnType = '\Swagger\Client\Model\ModelsSIPStat[]';
        $request = $this->iPStatRouterGetAllAggregatedSubAccountStatsForAnIPRequest($x_account_api_key, $ipid, $from, $to);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ModelsSIPStat[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation iPStatRouterGetAllAggregatedSubAccountStatsForAnIPAsync
     *
     * 
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function iPStatRouterGetAllAggregatedSubAccountStatsForAnIPAsync($x_account_api_key, $ipid, $from = null, $to = null)
    {
        return $this->iPStatRouterGetAllAggregatedSubAccountStatsForAnIPAsyncWithHttpInfo($x_account_api_key, $ipid, $from, $to)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation iPStatRouterGetAllAggregatedSubAccountStatsForAnIPAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function iPStatRouterGetAllAggregatedSubAccountStatsForAnIPAsyncWithHttpInfo($x_account_api_key, $ipid, $from = null, $to = null)
    {
        $returnType = '\Swagger\Client\Model\ModelsSIPStat[]';
        $request = $this->iPStatRouterGetAllAggregatedSubAccountStatsForAnIPRequest($x_account_api_key, $ipid, $from, $to);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'iPStatRouterGetAllAggregatedSubAccountStatsForAnIP'
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function iPStatRouterGetAllAggregatedSubAccountStatsForAnIPRequest($x_account_api_key, $ipid, $from = null, $to = null)
    {
        // verify the required parameter 'x_account_api_key' is set
        if ($x_account_api_key === null || (is_array($x_account_api_key) && count($x_account_api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_account_api_key when calling iPStatRouterGetAllAggregatedSubAccountStatsForAnIP'
            );
        }
        // verify the required parameter 'ipid' is set
        if ($ipid === null || (is_array($ipid) && count($ipid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ipid when calling iPStatRouterGetAllAggregatedSubAccountStatsForAnIP'
            );
        }

        $resourcePath = '/account/ip/stat/{ipid}/aggregate/subaccounts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // header params
        if ($x_account_api_key !== null) {
            $headerParams['X-Account-ApiKey'] = ObjectSerializer::toHeaderValue($x_account_api_key);
        }

        // path params
        if ($ipid !== null) {
            $resourcePath = str_replace(
                '{' . 'ipid' . '}',
                ObjectSerializer::toPathValue($ipid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation iPStatRouterGetAllIPStats
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ModelsRIPStat[]
     */
    public function iPStatRouterGetAllIPStats($x_account_api_key, $ipid, $from = null, $to = null)
    {
        list($response) = $this->iPStatRouterGetAllIPStatsWithHttpInfo($x_account_api_key, $ipid, $from, $to);
        return $response;
    }

    /**
     * Operation iPStatRouterGetAllIPStatsWithHttpInfo
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ModelsRIPStat[], HTTP status code, HTTP response headers (array of strings)
     */
    public function iPStatRouterGetAllIPStatsWithHttpInfo($x_account_api_key, $ipid, $from = null, $to = null)
    {
        $returnType = '\Swagger\Client\Model\ModelsRIPStat[]';
        $request = $this->iPStatRouterGetAllIPStatsRequest($x_account_api_key, $ipid, $from, $to);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ModelsRIPStat[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation iPStatRouterGetAllIPStatsAsync
     *
     * 
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function iPStatRouterGetAllIPStatsAsync($x_account_api_key, $ipid, $from = null, $to = null)
    {
        return $this->iPStatRouterGetAllIPStatsAsyncWithHttpInfo($x_account_api_key, $ipid, $from, $to)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation iPStatRouterGetAllIPStatsAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function iPStatRouterGetAllIPStatsAsyncWithHttpInfo($x_account_api_key, $ipid, $from = null, $to = null)
    {
        $returnType = '\Swagger\Client\Model\ModelsRIPStat[]';
        $request = $this->iPStatRouterGetAllIPStatsRequest($x_account_api_key, $ipid, $from, $to);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'iPStatRouterGetAllIPStats'
     *
     * @param  string $x_account_api_key Account API Key (required)
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function iPStatRouterGetAllIPStatsRequest($x_account_api_key, $ipid, $from = null, $to = null)
    {
        // verify the required parameter 'x_account_api_key' is set
        if ($x_account_api_key === null || (is_array($x_account_api_key) && count($x_account_api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_account_api_key when calling iPStatRouterGetAllIPStats'
            );
        }
        // verify the required parameter 'ipid' is set
        if ($ipid === null || (is_array($ipid) && count($ipid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ipid when calling iPStatRouterGetAllIPStats'
            );
        }

        $resourcePath = '/account/ip/stat/{ipid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // header params
        if ($x_account_api_key !== null) {
            $headerParams['X-Account-ApiKey'] = ObjectSerializer::toHeaderValue($x_account_api_key);
        }

        // path params
        if ($ipid !== null) {
            $resourcePath = str_replace(
                '{' . 'ipid' . '}',
                ObjectSerializer::toPathValue($ipid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation iPStatRouterGetAllIPStatsByGroup
     *
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $x_account_api_key Account API Key (required)
     * @param  string $provider the provider whose stats you want (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ModelsRIPStat[]
     */
    public function iPStatRouterGetAllIPStatsByGroup($ipid, $x_account_api_key, $provider, $from = null, $to = null)
    {
        list($response) = $this->iPStatRouterGetAllIPStatsByGroupWithHttpInfo($ipid, $x_account_api_key, $provider, $from, $to);
        return $response;
    }

    /**
     * Operation iPStatRouterGetAllIPStatsByGroupWithHttpInfo
     *
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $x_account_api_key Account API Key (required)
     * @param  string $provider the provider whose stats you want (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ModelsRIPStat[], HTTP status code, HTTP response headers (array of strings)
     */
    public function iPStatRouterGetAllIPStatsByGroupWithHttpInfo($ipid, $x_account_api_key, $provider, $from = null, $to = null)
    {
        $returnType = '\Swagger\Client\Model\ModelsRIPStat[]';
        $request = $this->iPStatRouterGetAllIPStatsByGroupRequest($ipid, $x_account_api_key, $provider, $from, $to);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ModelsRIPStat[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation iPStatRouterGetAllIPStatsByGroupAsync
     *
     * 
     *
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $x_account_api_key Account API Key (required)
     * @param  string $provider the provider whose stats you want (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function iPStatRouterGetAllIPStatsByGroupAsync($ipid, $x_account_api_key, $provider, $from = null, $to = null)
    {
        return $this->iPStatRouterGetAllIPStatsByGroupAsyncWithHttpInfo($ipid, $x_account_api_key, $provider, $from, $to)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation iPStatRouterGetAllIPStatsByGroupAsyncWithHttpInfo
     *
     * 
     *
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $x_account_api_key Account API Key (required)
     * @param  string $provider the provider whose stats you want (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function iPStatRouterGetAllIPStatsByGroupAsyncWithHttpInfo($ipid, $x_account_api_key, $provider, $from = null, $to = null)
    {
        $returnType = '\Swagger\Client\Model\ModelsRIPStat[]';
        $request = $this->iPStatRouterGetAllIPStatsByGroupRequest($ipid, $x_account_api_key, $provider, $from, $to);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'iPStatRouterGetAllIPStatsByGroup'
     *
     * @param  int $ipid the IPId you want to get (required)
     * @param  string $x_account_api_key Account API Key (required)
     * @param  string $provider the provider whose stats you want (required)
     * @param  string $from from date (optional)
     * @param  string $to to date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function iPStatRouterGetAllIPStatsByGroupRequest($ipid, $x_account_api_key, $provider, $from = null, $to = null)
    {
        // verify the required parameter 'ipid' is set
        if ($ipid === null || (is_array($ipid) && count($ipid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ipid when calling iPStatRouterGetAllIPStatsByGroup'
            );
        }
        // verify the required parameter 'x_account_api_key' is set
        if ($x_account_api_key === null || (is_array($x_account_api_key) && count($x_account_api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_account_api_key when calling iPStatRouterGetAllIPStatsByGroup'
            );
        }
        // verify the required parameter 'provider' is set
        if ($provider === null || (is_array($provider) && count($provider) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $provider when calling iPStatRouterGetAllIPStatsByGroup'
            );
        }

        $resourcePath = '/account/ip/stat/{ipid}/provider';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // query params
        if ($provider !== null) {
            $queryParams['provider'] = ObjectSerializer::toQueryValue($provider);
        }
        // header params
        if ($x_account_api_key !== null) {
            $headerParams['X-Account-ApiKey'] = ObjectSerializer::toHeaderValue($x_account_api_key);
        }

        // path params
        if ($ipid !== null) {
            $resourcePath = str_replace(
                '{' . 'ipid' . '}',
                ObjectSerializer::toPathValue($ipid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
