<?php
/**
 * ModelsQEmailMessage
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ModelsQEmailMessage Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ModelsQEmailMessage implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'models.QEmailMessage';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'account_id' => 'int',
        'amp_body' => 'string',
        'custom_fields' => 'object',
        'email_type' => 'string',
        'from' => '\Swagger\Client\Model\ModelsFrom',
        'groups' => 'object',
        'headers' => 'object',
        'html_body' => 'string',
        'ip_id' => 'int',
        'ip_pool' => 'string',
        'local_ip' => 'string',
        'message_id' => 'string',
        'pre_text' => 'string',
        'public_ip' => 'string',
        'reply_to' => '\Swagger\Client\Model\ModelsReplyTo',
        'sub_account_id' => 'int',
        'subject' => 'string',
        'submitted_at' => 'int',
        'text_body' => 'string',
        'to' => '\Swagger\Client\Model\ModelsTo',
        'track_clicks' => 'bool',
        'track_opens' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'account_id' => 'int64',
        'amp_body' => null,
        'custom_fields' => null,
        'email_type' => null,
        'from' => null,
        'groups' => null,
        'headers' => null,
        'html_body' => null,
        'ip_id' => 'int64',
        'ip_pool' => null,
        'local_ip' => null,
        'message_id' => null,
        'pre_text' => null,
        'public_ip' => null,
        'reply_to' => null,
        'sub_account_id' => 'int64',
        'subject' => null,
        'submitted_at' => 'int64',
        'text_body' => null,
        'to' => null,
        'track_clicks' => null,
        'track_opens' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_id' => 'accountID',
        'amp_body' => 'ampBody',
        'custom_fields' => 'customFields',
        'email_type' => 'emailType',
        'from' => 'from',
        'groups' => 'groups',
        'headers' => 'headers',
        'html_body' => 'htmlBody',
        'ip_id' => 'ipID',
        'ip_pool' => 'ipPool',
        'local_ip' => 'localIP',
        'message_id' => 'messageID',
        'pre_text' => 'preText',
        'public_ip' => 'publicIP',
        'reply_to' => 'replyTo',
        'sub_account_id' => 'subAccountID',
        'subject' => 'subject',
        'submitted_at' => 'submittedAt',
        'text_body' => 'textBody',
        'to' => 'to',
        'track_clicks' => 'trackClicks',
        'track_opens' => 'trackOpens'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account_id' => 'setAccountId',
        'amp_body' => 'setAmpBody',
        'custom_fields' => 'setCustomFields',
        'email_type' => 'setEmailType',
        'from' => 'setFrom',
        'groups' => 'setGroups',
        'headers' => 'setHeaders',
        'html_body' => 'setHtmlBody',
        'ip_id' => 'setIpId',
        'ip_pool' => 'setIpPool',
        'local_ip' => 'setLocalIp',
        'message_id' => 'setMessageId',
        'pre_text' => 'setPreText',
        'public_ip' => 'setPublicIp',
        'reply_to' => 'setReplyTo',
        'sub_account_id' => 'setSubAccountId',
        'subject' => 'setSubject',
        'submitted_at' => 'setSubmittedAt',
        'text_body' => 'setTextBody',
        'to' => 'setTo',
        'track_clicks' => 'setTrackClicks',
        'track_opens' => 'setTrackOpens'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_id' => 'getAccountId',
        'amp_body' => 'getAmpBody',
        'custom_fields' => 'getCustomFields',
        'email_type' => 'getEmailType',
        'from' => 'getFrom',
        'groups' => 'getGroups',
        'headers' => 'getHeaders',
        'html_body' => 'getHtmlBody',
        'ip_id' => 'getIpId',
        'ip_pool' => 'getIpPool',
        'local_ip' => 'getLocalIp',
        'message_id' => 'getMessageId',
        'pre_text' => 'getPreText',
        'public_ip' => 'getPublicIp',
        'reply_to' => 'getReplyTo',
        'sub_account_id' => 'getSubAccountId',
        'subject' => 'getSubject',
        'submitted_at' => 'getSubmittedAt',
        'text_body' => 'getTextBody',
        'to' => 'getTo',
        'track_clicks' => 'getTrackClicks',
        'track_opens' => 'getTrackOpens'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['account_id'] = isset($data['account_id']) ? $data['account_id'] : null;
        $this->container['amp_body'] = isset($data['amp_body']) ? $data['amp_body'] : null;
        $this->container['custom_fields'] = isset($data['custom_fields']) ? $data['custom_fields'] : null;
        $this->container['email_type'] = isset($data['email_type']) ? $data['email_type'] : null;
        $this->container['from'] = isset($data['from']) ? $data['from'] : null;
        $this->container['groups'] = isset($data['groups']) ? $data['groups'] : null;
        $this->container['headers'] = isset($data['headers']) ? $data['headers'] : null;
        $this->container['html_body'] = isset($data['html_body']) ? $data['html_body'] : null;
        $this->container['ip_id'] = isset($data['ip_id']) ? $data['ip_id'] : null;
        $this->container['ip_pool'] = isset($data['ip_pool']) ? $data['ip_pool'] : null;
        $this->container['local_ip'] = isset($data['local_ip']) ? $data['local_ip'] : null;
        $this->container['message_id'] = isset($data['message_id']) ? $data['message_id'] : null;
        $this->container['pre_text'] = isset($data['pre_text']) ? $data['pre_text'] : null;
        $this->container['public_ip'] = isset($data['public_ip']) ? $data['public_ip'] : null;
        $this->container['reply_to'] = isset($data['reply_to']) ? $data['reply_to'] : null;
        $this->container['sub_account_id'] = isset($data['sub_account_id']) ? $data['sub_account_id'] : null;
        $this->container['subject'] = isset($data['subject']) ? $data['subject'] : null;
        $this->container['submitted_at'] = isset($data['submitted_at']) ? $data['submitted_at'] : null;
        $this->container['text_body'] = isset($data['text_body']) ? $data['text_body'] : null;
        $this->container['to'] = isset($data['to']) ? $data['to'] : null;
        $this->container['track_clicks'] = isset($data['track_clicks']) ? $data['track_clicks'] : null;
        $this->container['track_opens'] = isset($data['track_opens']) ? $data['track_opens'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets account_id
     *
     * @return int
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param int $account_id account_id
     *
     * @return $this
     */
    public function setAccountId($account_id)
    {
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets amp_body
     *
     * @return string
     */
    public function getAmpBody()
    {
        return $this->container['amp_body'];
    }

    /**
     * Sets amp_body
     *
     * @param string $amp_body amp_body
     *
     * @return $this
     */
    public function setAmpBody($amp_body)
    {
        $this->container['amp_body'] = $amp_body;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return object
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param object $custom_fields custom_fields
     *
     * @return $this
     */
    public function setCustomFields($custom_fields)
    {
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }

    /**
     * Gets email_type
     *
     * @return string
     */
    public function getEmailType()
    {
        return $this->container['email_type'];
    }

    /**
     * Sets email_type
     *
     * @param string $email_type email_type
     *
     * @return $this
     */
    public function setEmailType($email_type)
    {
        $this->container['email_type'] = $email_type;

        return $this;
    }

    /**
     * Gets from
     *
     * @return \Swagger\Client\Model\ModelsFrom
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param \Swagger\Client\Model\ModelsFrom $from from
     *
     * @return $this
     */
    public function setFrom($from)
    {
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets groups
     *
     * @return object
     */
    public function getGroups()
    {
        return $this->container['groups'];
    }

    /**
     * Sets groups
     *
     * @param object $groups groups
     *
     * @return $this
     */
    public function setGroups($groups)
    {
        $this->container['groups'] = $groups;

        return $this;
    }

    /**
     * Gets headers
     *
     * @return object
     */
    public function getHeaders()
    {
        return $this->container['headers'];
    }

    /**
     * Sets headers
     *
     * @param object $headers headers
     *
     * @return $this
     */
    public function setHeaders($headers)
    {
        $this->container['headers'] = $headers;

        return $this;
    }

    /**
     * Gets html_body
     *
     * @return string
     */
    public function getHtmlBody()
    {
        return $this->container['html_body'];
    }

    /**
     * Sets html_body
     *
     * @param string $html_body html_body
     *
     * @return $this
     */
    public function setHtmlBody($html_body)
    {
        $this->container['html_body'] = $html_body;

        return $this;
    }

    /**
     * Gets ip_id
     *
     * @return int
     */
    public function getIpId()
    {
        return $this->container['ip_id'];
    }

    /**
     * Sets ip_id
     *
     * @param int $ip_id ip_id
     *
     * @return $this
     */
    public function setIpId($ip_id)
    {
        $this->container['ip_id'] = $ip_id;

        return $this;
    }

    /**
     * Gets ip_pool
     *
     * @return string
     */
    public function getIpPool()
    {
        return $this->container['ip_pool'];
    }

    /**
     * Sets ip_pool
     *
     * @param string $ip_pool ip_pool
     *
     * @return $this
     */
    public function setIpPool($ip_pool)
    {
        $this->container['ip_pool'] = $ip_pool;

        return $this;
    }

    /**
     * Gets local_ip
     *
     * @return string
     */
    public function getLocalIp()
    {
        return $this->container['local_ip'];
    }

    /**
     * Sets local_ip
     *
     * @param string $local_ip local_ip
     *
     * @return $this
     */
    public function setLocalIp($local_ip)
    {
        $this->container['local_ip'] = $local_ip;

        return $this;
    }

    /**
     * Gets message_id
     *
     * @return string
     */
    public function getMessageId()
    {
        return $this->container['message_id'];
    }

    /**
     * Sets message_id
     *
     * @param string $message_id message_id
     *
     * @return $this
     */
    public function setMessageId($message_id)
    {
        $this->container['message_id'] = $message_id;

        return $this;
    }

    /**
     * Gets pre_text
     *
     * @return string
     */
    public function getPreText()
    {
        return $this->container['pre_text'];
    }

    /**
     * Sets pre_text
     *
     * @param string $pre_text pre_text
     *
     * @return $this
     */
    public function setPreText($pre_text)
    {
        $this->container['pre_text'] = $pre_text;

        return $this;
    }

    /**
     * Gets public_ip
     *
     * @return string
     */
    public function getPublicIp()
    {
        return $this->container['public_ip'];
    }

    /**
     * Sets public_ip
     *
     * @param string $public_ip public_ip
     *
     * @return $this
     */
    public function setPublicIp($public_ip)
    {
        $this->container['public_ip'] = $public_ip;

        return $this;
    }

    /**
     * Gets reply_to
     *
     * @return \Swagger\Client\Model\ModelsReplyTo
     */
    public function getReplyTo()
    {
        return $this->container['reply_to'];
    }

    /**
     * Sets reply_to
     *
     * @param \Swagger\Client\Model\ModelsReplyTo $reply_to reply_to
     *
     * @return $this
     */
    public function setReplyTo($reply_to)
    {
        $this->container['reply_to'] = $reply_to;

        return $this;
    }

    /**
     * Gets sub_account_id
     *
     * @return int
     */
    public function getSubAccountId()
    {
        return $this->container['sub_account_id'];
    }

    /**
     * Sets sub_account_id
     *
     * @param int $sub_account_id sub_account_id
     *
     * @return $this
     */
    public function setSubAccountId($sub_account_id)
    {
        $this->container['sub_account_id'] = $sub_account_id;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string $subject subject
     *
     * @return $this
     */
    public function setSubject($subject)
    {
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets submitted_at
     *
     * @return int
     */
    public function getSubmittedAt()
    {
        return $this->container['submitted_at'];
    }

    /**
     * Sets submitted_at
     *
     * @param int $submitted_at submitted_at
     *
     * @return $this
     */
    public function setSubmittedAt($submitted_at)
    {
        $this->container['submitted_at'] = $submitted_at;

        return $this;
    }

    /**
     * Gets text_body
     *
     * @return string
     */
    public function getTextBody()
    {
        return $this->container['text_body'];
    }

    /**
     * Sets text_body
     *
     * @param string $text_body text_body
     *
     * @return $this
     */
    public function setTextBody($text_body)
    {
        $this->container['text_body'] = $text_body;

        return $this;
    }

    /**
     * Gets to
     *
     * @return \Swagger\Client\Model\ModelsTo
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param \Swagger\Client\Model\ModelsTo $to to
     *
     * @return $this
     */
    public function setTo($to)
    {
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets track_clicks
     *
     * @return bool
     */
    public function getTrackClicks()
    {
        return $this->container['track_clicks'];
    }

    /**
     * Sets track_clicks
     *
     * @param bool $track_clicks track_clicks
     *
     * @return $this
     */
    public function setTrackClicks($track_clicks)
    {
        $this->container['track_clicks'] = $track_clicks;

        return $this;
    }

    /**
     * Gets track_opens
     *
     * @return bool
     */
    public function getTrackOpens()
    {
        return $this->container['track_opens'];
    }

    /**
     * Sets track_opens
     *
     * @param bool $track_opens track_opens
     *
     * @return $this
     */
    public function setTrackOpens($track_opens)
    {
        $this->container['track_opens'] = $track_opens;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


