<?php
/**
 * ModelsWMessageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ModelsWMessageTest Class Doc Comment
 *
 * @category    Class
 * @description ModelsWMessage
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ModelsWMessageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ModelsWMessage"
     */
    public function testModelsWMessage()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "groups"
     */
    public function testPropertyGroups()
    {
    }

    /**
     * Test attribute "ipid"
     */
    public function testPropertyIpid()
    {
    }

    /**
     * Test attribute "message_type"
     */
    public function testPropertyMessageType()
    {
    }

    /**
     * Test attribute "message_uuid"
     */
    public function testPropertyMessageUuid()
    {
    }

    /**
     * Test attribute "mock_message"
     */
    public function testPropertyMockMessage()
    {
    }

    /**
     * Test attribute "mock_time_shift"
     */
    public function testPropertyMockTimeShift()
    {
    }

    /**
     * Test attribute "smtp_code"
     */
    public function testPropertySmtpCode()
    {
    }

    /**
     * Test attribute "smtp_description"
     */
    public function testPropertySmtpDescription()
    {
    }

    /**
     * Test attribute "sub_account_id"
     */
    public function testPropertySubAccountId()
    {
    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
