<?php
/**
 * ModelsEAccountMemberTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ModelsEAccountMemberTest Class Doc Comment
 *
 * @category    Class
 * @description ModelsEAccountMember
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ModelsEAccountMemberTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ModelsEAccountMember"
     */
    public function testModelsEAccountMember()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "current_email_service_provider"
     */
    public function testPropertyCurrentEmailServiceProvider()
    {
    }

    /**
     * Test attribute "industry"
     */
    public function testPropertyIndustry()
    {
    }

    /**
     * Test attribute "logo_url"
     */
    public function testPropertyLogoUrl()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "onboard_c_finished"
     */
    public function testPropertyOnboardCFinished()
    {
    }

    /**
     * Test attribute "onboard_q_answered"
     */
    public function testPropertyOnboardQAnswered()
    {
    }

    /**
     * Test attribute "phone_number"
     */
    public function testPropertyPhoneNumber()
    {
    }

    /**
     * Test attribute "sending_volume_per_month"
     */
    public function testPropertySendingVolumePerMonth()
    {
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
    }

    /**
     * Test attribute "verify_email"
     */
    public function testPropertyVerifyEmail()
    {
    }
}
