<?php
/**
 * ModelsRSuppressionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ModelsRSuppressionTest Class Doc Comment
 *
 * @category    Class
 * @description ModelsRSuppression
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ModelsRSuppressionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ModelsRSuppression"
     */
    public function testModelsRSuppression()
    {
    }

    /**
     * Test attribute "hard_bounce"
     */
    public function testPropertyHardBounce()
    {
    }

    /**
     * Test attribute "manual"
     */
    public function testPropertyManual()
    {
    }

    /**
     * Test attribute "spam_complaint"
     */
    public function testPropertySpamComplaint()
    {
    }

    /**
     * Test attribute "unsubscribe"
     */
    public function testPropertyUnsubscribe()
    {
    }
}
