<?php
/**
 * AccountsubaccountApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AccountsubaccountApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountsubaccountApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for subAccountRouterCount
     *
     * .
     *
     */
    public function testSubAccountRouterCount()
    {
    }

    /**
     * Test case for subAccountRouterCreate
     *
     * .
     *
     */
    public function testSubAccountRouterCreate()
    {
    }

    /**
     * Test case for subAccountRouterDelete
     *
     * .
     *
     */
    public function testSubAccountRouterDelete()
    {
    }

    /**
     * Test case for subAccountRouterGet
     *
     * .
     *
     */
    public function testSubAccountRouterGet()
    {
    }

    /**
     * Test case for subAccountRouterGetAll
     *
     * .
     *
     */
    public function testSubAccountRouterGetAll()
    {
    }

    /**
     * Test case for subAccountRouterUpdate
     *
     * .
     *
     */
    public function testSubAccountRouterUpdate()
    {
    }
}
