<?php
/**
 * AccountincidentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AccountincidentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountincidentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for incidentRouterAdd
     *
     * .
     *
     */
    public function testIncidentRouterAdd()
    {
    }

    /**
     * Test case for incidentRouterCount
     *
     * .
     *
     */
    public function testIncidentRouterCount()
    {
    }

    /**
     * Test case for incidentRouterCreate
     *
     * .
     *
     */
    public function testIncidentRouterCreate()
    {
    }

    /**
     * Test case for incidentRouterGetAll
     *
     * .
     *
     */
    public function testIncidentRouterGetAll()
    {
    }

    /**
     * Test case for incidentRouterGetAllComments
     *
     * .
     *
     */
    public function testIncidentRouterGetAllComments()
    {
    }

    /**
     * Test case for incidentRouterGetIncident
     *
     * .
     *
     */
    public function testIncidentRouterGetIncident()
    {
    }

    /**
     * Test case for incidentRouterUpdate
     *
     * .
     *
     */
    public function testIncidentRouterUpdate()
    {
    }
}
