<?php
/**
 * AccountwebhookApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AccountwebhookApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountwebhookApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for accountWebhookRouterCount
     *
     * .
     *
     */
    public function testAccountWebhookRouterCount()
    {
    }

    /**
     * Test case for accountWebhookRouterCreate
     *
     * .
     *
     */
    public function testAccountWebhookRouterCreate()
    {
    }

    /**
     * Test case for accountWebhookRouterCreateAccountWebhookInAccountWebhookCache
     *
     * .
     *
     */
    public function testAccountWebhookRouterCreateAccountWebhookInAccountWebhookCache()
    {
    }

    /**
     * Test case for accountWebhookRouterDelete
     *
     * .
     *
     */
    public function testAccountWebhookRouterDelete()
    {
    }

    /**
     * Test case for accountWebhookRouterDeleteAccountWebhookInAccountWebhookCache
     *
     * .
     *
     */
    public function testAccountWebhookRouterDeleteAccountWebhookInAccountWebhookCache()
    {
    }

    /**
     * Test case for accountWebhookRouterGet
     *
     * .
     *
     */
    public function testAccountWebhookRouterGet()
    {
    }

    /**
     * Test case for accountWebhookRouterGetAll
     *
     * .
     *
     */
    public function testAccountWebhookRouterGetAll()
    {
    }

    /**
     * Test case for accountWebhookRouterUpdate
     *
     * .
     *
     */
    public function testAccountWebhookRouterUpdate()
    {
    }
}
