<?php
/**
 * AccountipApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AccountipApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountipApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for iPRouterAllocateIP
     *
     * .
     *
     */
    public function testIPRouterAllocateIP()
    {
    }

    /**
     * Test case for iPRouterCount
     *
     * .
     *
     */
    public function testIPRouterCount()
    {
    }

    /**
     * Test case for iPRouterDelete
     *
     * .
     *
     */
    public function testIPRouterDelete()
    {
    }

    /**
     * Test case for iPRouterGet
     *
     * .
     *
     */
    public function testIPRouterGet()
    {
    }

    /**
     * Test case for iPRouterGetAll
     *
     * .
     *
     */
    public function testIPRouterGetAll()
    {
    }

    /**
     * Test case for iPRouterUpdate
     *
     * .
     *
     */
    public function testIPRouterUpdate()
    {
    }
}
